# Generated by Django 4.0.2 on 2022-03-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='details',
            new_name='detail',
        ),
    ]
