# Generated by Django 4.0.4 on 2022-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='/media/1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
