# Generated by Django 4.0.4 on 2022-05-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_code',
            new_name='category',
        ),
    ]
