# Generated by Django 4.0.4 on 2022-05-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Store Code')),
                ('description', models.CharField(max_length=50, verbose_name='Store Description')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='Store Detail')),
                ('latitude', models.FloatField(verbose_name='Store Latitude')),
                ('longitude', models.FloatField(verbose_name='Store Longitude')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_location_code'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('tenant', 'description'), name='unique_location_description'),
        ),
    ]
