# Generated by Django 4.0.4 on 2022-05-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_location_code',
        ),
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_location_description',
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_store_code'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('tenant', 'description'), name='unique_store_description'),
        ),
    ]
