# Generated by Django 4.0.4 on 2022-05-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
        ('Product', '0004_alter_product_options_alter_product_category_and_more'),
        ('Store', '0002_remove_store_unique_location_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.CreateModel(
            name='ProductInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_price', models.FloatField(verbose_name='Product List Price')),
                ('discounted_price', models.FloatField(verbose_name='Product Discounted Price')),
                ('active', models.BooleanField(verbose_name='Product Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product', verbose_name='Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.store', verbose_name='Store')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product in Store',
                'verbose_name_plural': 'Products in Store',
                'ordering': ['store', 'product'],
            },
        ),
        migrations.AddConstraint(
            model_name='productinstore',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'store'), name='unique_store_product'),
        ),
    ]
